default-resources:
  - runtime=120
  - mem_mb=64000
  - slurm_partition=cbcb
  - slurm_account=cbcb
  - tasks=1
  - nodes=1
  - cpus_per_task=4
set-threads:
  create_std_kraken2_database: 16
  divide_database: 16
set-resources:
  align_trimmed_reads_to_index:
    mem_mb: 256000
    tasks: 1
    cpus_per_task: 8
  create_std_kraken2_database:
    runtime: 600
    tasks: 1
    cpus_per_task: 16
  divide_database:
    tasks: 1
    cpus_per_task: 16
  interleave:
    mem_mb: 16000
  deinterleave:
    mem_mb: 16000
conda-frontend: mamba
directory: workdir/
drop-metadata: True
executor: slurm
jobs: 4
keep-going: True
rerun-incomplete: True
restart-times: 0
use-conda: True